/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract
         * @description Upload lab report PDFs and extract biomarkers into a LabReport.
         *     Result is stored in the patient session for downstream phases.
         */
        post: operations["extract_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Interview
         * @description Extract symptom entities from free-text narrative and optional images/video.
         *     Result is stored in the patient session.
         */
        post: operations["interview_interview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Research
         * @description Run RAG retrieval against the PubMed vector store.
         *     Requires a live Databricks Vector Search index; returns 503 if unavailable.
         *     Returns a job_id immediately; poll GET /jobs/{job_id} for the result.
         */
        post: operations["research_research_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Route
         * @description Score cluster alignment and disease candidates.
         *     Pulls lab_report, interview_result, and research_result from the session.
         *     Runs in heuristic mode (no GPU required).
         */
        post: operations["route_route_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Translate
         * @description Generate SOAP note + Layman's Compass from all prior phase results.
         *     Uses fallback templates if vLLM is not available.
         *     Pulls all results from the patient session.
         */
        post: operations["translate_translate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moderate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Moderate
         * @description Two-stage content moderation for forum posts.
         *     Stage 1: DistilBERT binary classifier (fast).
         *     Stage 2: Drug/dosage NER + decision logic (only on Stage 1 positives).
         *     Stateless — no session required.
         */
        post: operations["moderate_moderate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Full Pipeline
         * @description End-to-end pipeline in a single request.
         *     Runs: extract → interview → (research if Databricks available) → route → translate.
         *     Dispatched as a background task; use GET /stream/{patient_id} or GET /jobs/{job_id}.
         */
        post: operations["full_pipeline_pipeline_full_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream
         * @description Server-Sent Events stream of ThoughtStream events for a patient session.
         *     Holds the connection open until a 'done' or 'error' event is received,
         *     or the client disconnects.
         *
         *     Events are JSON objects, e.g.:
         *         {"agent": "The Extractor", "step": "bio_fingerprint", "summary": "...", "patient_id": "P001"}
         *         {"type": "progress", "phase": "route", "detail": "Scoring cluster alignment"}
         *         {"type": "done", "job_id": "..."}
         */
        get: operations["stream_stream__patient_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Status
         * @description Poll for the result of a background task (research, full pipeline).
         *
         *     status values:
         *       - queued   — task is waiting to start
         *       - running  — task is in progress
         *       - done     — task completed; result is populated
         *       - error    — task failed; error message is populated
         */
        get: operations["get_job_status_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Results
         * @description Return all pipeline outputs stored in the patient session.
         *
         *     Returns 404 if no session exists for the given patient_id.
         *     Fields are null for pipeline phases that have not yet completed.
         */
        get: operations["get_results_results__patient_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BioFingerprint */
        BioFingerprint: {
            /** Nlr */
            NLR?: components["schemas"]["RatioTimepoint"][];
            /** Plr */
            PLR?: components["schemas"]["RatioTimepoint"][];
            /** Mlr */
            MLR?: components["schemas"]["RatioTimepoint"][];
            /** Sii */
            SII?: components["schemas"]["RatioTimepoint"][];
            /** Crp Albumin */
            CRP_Albumin?: components["schemas"]["RatioTimepoint"][];
            /** C3 C4 */
            C3_C4?: components["schemas"]["RatioTimepoint"][];
            ANA_titer_trend?: components["schemas"]["Trend"] | null;
            /** Sustained Abnormalities */
            sustained_abnormalities?: string[];
            /** Morphological Shifts */
            morphological_shifts?: string[];
        };
        /** Body_extract_extract_post */
        Body_extract_extract_post: {
            /** Patient Id */
            patient_id: string;
            /**
             * Patient Age
             * @default 40
             */
            patient_age: number;
            /**
             * Patient Sex
             * @default F
             */
            patient_sex: string;
            /**
             * Files
             * @default []
             */
            files: string[];
        };
        /** Body_full_pipeline_pipeline_full_post */
        Body_full_pipeline_pipeline_full_post: {
            /** Patient Id */
            patient_id: string;
            /** Symptom Text */
            symptom_text: string;
            /**
             * Patient Age
             * @default 40
             */
            patient_age: number;
            /**
             * Patient Sex
             * @default F
             */
            patient_sex: string;
            /**
             * Medications
             * @default
             */
            medications: string;
            /**
             * Pdfs
             * @default []
             */
            pdfs: string[];
            /**
             * Images
             * @default []
             */
            images: string[];
        };
        /** Body_interview_interview_post */
        Body_interview_interview_post: {
            /** Patient Id */
            patient_id: string;
            /** Symptom Text */
            symptom_text: string;
            /**
             * Images
             * @default []
             */
            images: string[];
            /**
             * Videos
             * @default []
             */
            videos: string[];
        };
        /**
         * Cluster
         * @enum {string}
         */
        Cluster: "Systemic" | "Gastrointestinal" | "Endocrine";
        /** DiseaseCandidate */
        DiseaseCandidate: {
            /** Disease */
            disease: string;
            /** Disease Alignment Score */
            disease_alignment_score: number;
            /** Supporting Dois */
            supporting_dois?: string[];
            /** Criteria Met */
            criteria_met?: string[];
            /**
             * Criteria Count
             * @default 0
             */
            criteria_count: number;
            /**
             * Criteria Cap Applied
             * @default false
             */
            criteria_cap_applied: boolean;
            /**
             * Drug Induced Flag
             * @default false
             */
            drug_induced_flag: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InterviewResult */
        InterviewResult: {
            /** Patient Id */
            patient_id: string;
            /** Raw Text */
            raw_text: string;
            /** Symptoms */
            symptoms?: components["schemas"]["SymptomEntity"][];
            /** Visual Keywords */
            visual_keywords?: string[];
            thought_stream_event?: components["schemas"]["ThoughtStreamEvent"] | null;
        };
        /** LabReport */
        LabReport: {
            /** Patient Id */
            patient_id: string;
            /** Markers */
            markers?: components["schemas"]["MarkerTimeline"][];
            bio_fingerprint?: components["schemas"]["BioFingerprint"];
            thought_stream_event?: components["schemas"]["ThoughtStreamEvent"] | null;
        };
        /**
         * MarkerFlag
         * @enum {string}
         */
        MarkerFlag: "HIGH" | "LOW" | "NORMAL";
        /** MarkerTimeline */
        MarkerTimeline: {
            /** Loinc Code */
            loinc_code: string | null;
            /** Display Name */
            display_name: string;
            /** Values */
            values: components["schemas"]["MarkerValue"][];
            trend?: components["schemas"]["Trend"] | null;
        };
        /** MarkerValue */
        MarkerValue: {
            /** Loinc Code */
            loinc_code?: string | null;
            /** Display Name */
            display_name: string;
            /** Date */
            date: string;
            /** Value */
            value: number;
            /** Unit */
            unit: string;
            /** Ref Range Low */
            ref_range_low?: number | null;
            /** Ref Range High */
            ref_range_high?: number | null;
            /** @default NORMAL */
            flag: components["schemas"]["MarkerFlag"];
            /** Z Score Nhanes */
            z_score_nhanes?: number | null;
        };
        /** ModerateRequest */
        ModerateRequest: {
            /** Post Id */
            post_id: string;
            /** Text */
            text: string;
            /** User Id */
            user_id?: string | null;
        };
        /** RatioTimepoint */
        RatioTimepoint: {
            /** Date */
            date: string;
            /** Value */
            value: number;
            /** Flag */
            flag?: string | null;
        };
        /** ResearchRequest */
        ResearchRequest: {
            /** Patient Id */
            patient_id: string;
            /** Cluster Hint */
            cluster_hint?: string | null;
        };
        /** ResearchResult */
        ResearchResult: {
            /** Patient Id */
            patient_id: string;
            /** Sub Queries */
            sub_queries: string[];
            /** Passages */
            passages: components["schemas"]["RetrievedPassage"][];
            thought_stream_event?: components["schemas"]["ThoughtStreamEvent"] | null;
        };
        /** ResultsResponse */
        ResultsResponse: {
            /** Patient Id */
            patient_id: string;
            lab_report?: components["schemas"]["LabReport"] | null;
            interview_result?: components["schemas"]["InterviewResult"] | null;
            research_result?: components["schemas"]["ResearchResult"] | null;
            router_output?: components["schemas"]["RouterOutput"] | null;
            translator_output?: components["schemas"]["TranslatorOutput"] | null;
        };
        /** RetrievedPassage */
        RetrievedPassage: {
            /** Chunk Id */
            chunk_id: string;
            /** Doi */
            doi: string | null;
            /** Journal */
            journal: string | null;
            /** Year */
            year: number | null;
            /** Section */
            section: string | null;
            cluster_tag: components["schemas"]["Cluster"] | null;
            /** Text */
            text: string;
            /** Score */
            score: number;
        };
        /** RouteRequest */
        RouteRequest: {
            /** Patient Id */
            patient_id: string;
            /**
             * Medications
             * @default []
             */
            medications: string[];
            /**
             * Patient Age
             * @default 40
             */
            patient_age: number;
            /**
             * Patient Sex
             * @default F
             */
            patient_sex: string;
        };
        /** RouterOutput */
        RouterOutput: {
            /** Patient Id */
            patient_id: string;
            cluster: components["schemas"]["Cluster"];
            /** Cluster Alignment Score */
            cluster_alignment_score: number;
            /** Routing Recommendation */
            routing_recommendation: string;
            /** Disease Candidates */
            disease_candidates: components["schemas"]["DiseaseCandidate"][];
            thought_stream_event?: components["schemas"]["ThoughtStreamEvent"] | null;
        };
        /** SymptomEntity */
        SymptomEntity: {
            /** Entity */
            entity: string;
            /** Location */
            location?: string | null;
            /** Duration Months */
            duration_months?: number | null;
            /** Severity */
            severity?: string | null;
            /** Onset */
            onset?: string | null;
            cluster_signal?: components["schemas"]["Cluster"] | null;
            /** Snomed Concept */
            snomed_concept?: string | null;
        };
        /** ThoughtStreamEvent */
        ThoughtStreamEvent: {
            /** Agent */
            agent: string;
            /** Step */
            step: string;
            /** Summary */
            summary: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
        /** TranslateRequest */
        TranslateRequest: {
            /** Patient Id */
            patient_id: string;
        };
        /** TranslatorOutput */
        TranslatorOutput: {
            /** Patient Id */
            patient_id: string;
            /** Soap Note */
            soap_note: string;
            /** Layman Compass */
            layman_compass: string;
            /** Faithfulness Score */
            faithfulness_score: number;
            /** Flagged Sentences */
            flagged_sentences?: string[];
            /** Fk Grade Level */
            fk_grade_level?: number | null;
            thought_stream_event?: components["schemas"]["ThoughtStreamEvent"] | null;
        };
        /**
         * Trend
         * @enum {string}
         */
        Trend: "stable" | "escalating" | "resolving";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    extract_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interview_interview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_interview_interview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_research_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_route_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    translate_translate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    moderate_moderate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    full_pipeline_pipeline_full_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_full_pipeline_pipeline_full_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_stream__patient_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_status_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_results_results__patient_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
